### ISSUE TITLE
Player collision vibrations

### ISSUE THREAD

**Issue by quigley-c** [codeandkey/boom#23]
# Player Collision vibrations
The player seems to vibrate on the ground.

## What's the issue?
With some of the new PR's coming in it's becoming more apparent that the player isn't actually motionless on the ground. Specifically, he is constantly vibrating vertically possibly due to the collision checking on the ground.

**Comment by codeandkey** [comment]
This is due to slight inconsistencies between AABB testing and how the game resolves player collisions with variable delta time. The player's lower `y` bound will fluctuate between `0` and `1` above the ground which causes the vibrations. The `math.floor()` calls in the player render should make it undetectable but is definitely a better way to handle it. I'll take a closer look at collision resolving, perhaps we could perform AABB based on "pixel" locations instead of exact (subpixel) locations.
